### ISSUE TITLE
Can you please tag a release?

### ISSUE THREAD

**Issue by ltworf** [taisei-project/python-zipfile-zstd#4]
Hello,

I'm working on packaging this for debian. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087823

But normally in Debian we work with sources and not binaries, and so we prefer to get the sources from github rather than pypi.

This project has version 0.0.4 on pypi, but here on git there are no tagged releases. Which are what I'd like to use as source.

Would it be ok for you to use `git tag` to tag a release, so I can use a "fixed" point as origin for the package?

Thanks for your useful library.

**Comment by Akaricchi** [comment]
I've just pushed a signed tag for the [v0.0.4](https://github.com/taisei-project/python-zipfile-zstd/releases/tag/v0.0.4) release.

I've also discovered that I somehow forgot to push the 3-year-old commit that actually bumped the version to 0.0.4. Oops. So I did that now too. Thanks for bringing this to my attention.

**Comment by ltworf** [comment]
Ah thanks for doing it so soon.
